data:
  image: busybox
  volumes:
    - /var/lib/postgresql/data
  entrypoint: /bin/true

logs:
  image: busybox
  volumes:
    - /logs/sherpa
    - /logs/nginx
  entrypoint: /bin/true

#focus:
#  image: turistforeningen/sherpa-focus:latest
#  volumes:
#    - private-data:/private-data:ro

postgres:
  image: turistforeningen/sherpa-postgres:latest
  volumes_from:
    - data

psql:
  image: turistforeningen/sherpa-postgres:latest
  volumes:
    - private-data:/private-data:ro
  links:
    - postgres
  command: /bin/true

www:
  image: turistforeningen/sherpa-nginx:latest
  links:
    - sherpa
  volumes_from:
    - logs
  volumes:
    - static:/sherpa/static:ro
  ports:
    - "8080"

sherpa:
  build: .
  links:
    - postgres:postgres
  #  - focus:focus
  volumes_from:
    - logs
  volumes:
    - gunicorn.py:/sherpa/gunicorn.py
    - apps/:/sherpa/apps
    - locale/:sherpa/locale
    - sherpa/:sherpa/sherpa
    - templates/:sherpa/templates
    - private-data:/private-data:ro
  environment:
    DJANGO_CONFIGURATION: dev
    DJANGO_SETTINGS_MODULE: sherpa.settings
    PYTHONUNBUFFERED: 0
  command: gunicorn -c gunicorn.py sherpa.wsgi:application

builder:
  build: static/
  volumes:
    - static/less:/usr/src/app/less
    - static/css:/usr/src/app/css
    - static/lib:/usr/src/app/lib
    - static/dist/usr/src/app/dist
    - static/polymer:/usr/src/app/polymer
    - static/bower_components:/usr/src/app/bower_components
  environment:
    NODE_ENV: development
  command: npm run-script build

