from django.db import models

class Cabin(models.Model):
    ca_id = models.IntegerField(primary_key=True)
    ca_nr = models.IntegerField(null=True, blank=True)
    ca_name = models.TextField()
    ca_name_official = models.TextField(blank=True)
    ca_alias = models.TextField(blank=True)
    ca_service = models.TextField(blank=True)
    ca_type = models.TextField(blank=True)
    ca_built = models.TextField(blank=True)
    ca_content = models.TextField(blank=True)
    ca_content_extended = models.TextField(blank=True)
    ca_owner = models.IntegerField()
    ca_maintainer = models.IntegerField()
    ca_beds_b = models.IntegerField(null=True, blank=True)
    ca_beds_s = models.IntegerField(null=True, blank=True)
    ca_beds_u = models.IntegerField(null=True, blank=True)
    ca_beds_winter = models.IntegerField(null=True, blank=True)
    ca_beds_extras = models.IntegerField(null=True, blank=True)
    ca_location = models.TextField(blank=True)
    ca_altitude = models.IntegerField(null=True, blank=True)
    ca_utm = models.TextField(blank=True)
    ca_utm_gps = models.TextField(blank=True)
    ca_m711 = models.TextField(blank=True)
    ca_m711_nb = models.TextField(blank=True)
    ca_map = models.TextField(blank=True)
    ca_map_nb = models.TextField(blank=True)
    ca_lon = models.DecimalField(null=True, max_digits=65535, decimal_places=65535, blank=True)
    ca_lat = models.DecimalField(null=True, max_digits=65535, decimal_places=65535, blank=True)
    ca_ssr_id = models.IntegerField(null=True, blank=True)
    ca_ssr_obj_id = models.IntegerField(null=True, blank=True)
    ca_ssr_type_id = models.IntegerField(null=True, blank=True)
    ca_ssr_type = models.TextField(blank=True)
    ca_municipality_id = models.IntegerField(null=True, blank=True)
    ca_municipality = models.TextField(blank=True)
    ca_county = models.TextField(blank=True)
    ca_yr_url = models.TextField(blank=True)
    ca_contact_in_season = models.TextField(blank=True)
    ca_address_in_season = models.TextField(blank=True)
    ca_mobile_in_season = models.TextField(blank=True)
    ca_phone_in_season = models.TextField(blank=True)
    ca_fax_in_season = models.TextField(blank=True)
    ca_email_in_season = models.TextField(blank=True)
    ca_contact_out_of_season = models.TextField(blank=True)
    ca_address_out_of_season = models.TextField(blank=True)
    ca_mobile_out_of_season = models.TextField(blank=True)
    ca_phone_out_of_season = models.TextField(blank=True)
    ca_fax_out_of_season = models.TextField(blank=True)
    ca_email_out_of_season = models.TextField(blank=True)
    ca_url = models.TextField(blank=True)
    ca_content_nno = models.TextField(blank=True)
    ca_content_eng = models.TextField(blank=True)
    ca_content_ger = models.TextField(blank=True)
    ca_access_summer = models.TextField(blank=True)
    ca_access_winter = models.TextField(blank=True)
    ca_access = models.TextField(blank=True)
    ca_price = models.TextField(blank=True)
    ca_album = models.TextField(blank=True)
    ca_startdate = models.TextField(blank=True)
    ca_extras = models.TextField(blank=True)
    ca_source = models.TextField(blank=True)
    ca_status = models.TextField(blank=True)
    ca_modified = models.DateTimeField(null=True, blank=True)
    ca_online = models.IntegerField(null=True, blank=True)
    ca_modified_by = models.IntegerField(null=True, blank=True)
    ca_content_fre = models.TextField(blank=True)
    ca_booking_url = models.TextField(blank=True)
    ca_url_ut = models.TextField(blank=True)
    the_geom = models.TextField(blank=True) # This field type is a guess.
    class Meta:
        db_table = u'cabin2'
