# encoding: utf-8
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

urlpatterns = patterns('',
    # Keep old admin-ui for now (difference is /admin/ vs /sherpa/)
    url(r'^admin/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://%s/admin/' % settings.OLD_SITE}),

    # Keep old user page
    # Note: This URL uses hardcoded links in enrollment result pages and email receipts.
    url(r'^minside/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://%s/minside/' % settings.OLD_SITE}),
    url(r'^fjelltreffen/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://%s/fjelltreffen/' % settings.OLD_SITE}),

    # Old images
    url(r'^images/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://%s/images/' % settings.OLD_SITE}),
    url(r'^album/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://%s/album/' % settings.OLD_SITE}),

    # All sites go to old pages with subdomain
    url(ur'^alesund/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://alesund.turistforeningen.no/', 'permanent': True}),
    url(ur'^alta/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://alta.turistforeningen.no/', 'permanent': True}),
    url(ur'^ardal/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://ardal.turistforeningen.no/', 'permanent': True}),
    url(ur'^askoy/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://askoy.turistforeningen.no/', 'permanent': True}),
    url(ur'^aust-agder/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://aust-agder.turistforeningen.no/', 'permanent': True}),
    url(ur'^austevoll/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://austevoll.turistforeningen.no/', 'permanent': True}),
    url(ur'^baerum/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://baerum.turistforeningen.no/', 'permanent': True}),
    url(ur'^balestrand/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://balestrand.turistforeningen.no/', 'permanent': True}),
    url(ur'^bergen/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://bergen.turistforeningen.no/', 'permanent': True}),
    url(ur'^bjornhollia/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://bjornhollia.turistforeningen.no/', 'permanent': True}),
    url(ur'^bomlo/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://bomlo.turistforeningen.no/', 'permanent': True}),
    url(ur'^bronnoysund/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://bronnoysund.turistforeningen.no/', 'permanent': True}),
    url(ur'^brurskanken/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://brurskanken.turistforeningen.no/', 'permanent': True}),
    url(ur'^deutsch/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://deutsch.turistforeningen.no/', 'permanent': True}),
    url(ur'^drammen/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://drammen.turistforeningen.no/', 'permanent': True}),
    url(ur'^eidsvoll/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://eidsvoll.turistforeningen.no/', 'permanent': True}),
    url(ur'^elverum/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://elverum.turistforeningen.no/', 'permanent': True}),
    url(ur'^english/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://english.turistforeningen.no/', 'permanent': True}),
    url(ur'^etne/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://etne.turistforeningen.no/', 'permanent': True}),
    url(ur'^fannarakhytta/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://fannarakhytta.turistforeningen.no/', 'permanent': True}),
    url(ur'^finnskogen/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://finnskogen.turistforeningen.no/', 'permanent': True}),
    url(ur'^finsehytta/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://finsehytta.turistforeningen.no/', 'permanent': True}),
    url(ur'^flekkefjord/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://flekkefjord.turistforeningen.no/', 'permanent': True}),
    url(ur'^flora/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://flora.turistforeningen.no/', 'permanent': True}),
    url(ur'^fondsbu/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://fondsbu.turistforeningen.no/', 'permanent': True}),
    url(ur'^foreningsnett/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://foreningsnett.turistforeningen.no/', 'permanent': True}),
    url(ur'^fosen/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://fosen.turistforeningen.no/', 'permanent': True}),
    url(ur'^francais/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://francais.turistforeningen.no/', 'permanent': True}),
    url(ur'^gaustatoppen/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://gaustatoppen.turistforeningen.no/', 'permanent': True}),
    url(ur'^geiterygghytta/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://geiterygghytta.turistforeningen.no/', 'permanent': True}),
    url(ur'^gjendebu/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://gjendebu.turistforeningen.no/', 'permanent': True}),
    url(ur'^gjendesheim/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://gjendesheim.turistforeningen.no/', 'permanent': True}),
    url(ur'^gjovik/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://gjovik.turistforeningen.no/', 'permanent': True}),
    url(ur'^glitterheim/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://glitterheim.turistforeningen.no/', 'permanent': True}),
    url(ur'^grimsdalshytta/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://grimsdalshytta.turistforeningen.no/', 'permanent': True}),
    url(ur'^gudbrandsdalen/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://gudbrandsdalen.turistforeningen.no/', 'permanent': True}),
    url(ur'^gulen/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://gulen.turistforeningen.no/', 'permanent': True}),
    url(ur'^hadeland/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://hadeland.turistforeningen.no/', 'permanent': True}),
    url(ur'^hammerfest/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://hammerfest.turistforeningen.no/', 'permanent': True}),
    url(ur'^haugesund/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://haugesund.turistforeningen.no/', 'permanent': True}),
    url(ur'^havrefjell/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://havrefjell.turistforeningen.no/', 'permanent': True}),
    url(ur'^hemsedal/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://hemsedal.turistforeningen.no/', 'permanent': True}),
    url(ur'^holmdstrand/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://holmdstrand.turistforeningen.no/', 'permanent': True}),
    url(ur'^holmestrand/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://holmestrand.turistforeningen.no/', 'permanent': True}),
    url(ur'^horten/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://horten.turistforeningen.no/', 'permanent': True}),
    url(ur'^indrenordfjord/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://indrenordfjord.turistforeningen.no/', 'permanent': True}),
    url(ur'^indreostfold/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://indreostfold.turistforeningen.no/', 'permanent': True}),
    url(ur'^iungsdalshytta/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://iungsdalshytta.turistforeningen.no/', 'permanent': True}),
    url(ur'^jotunheimstien/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://jotunheimstien.turistforeningen.no/', 'permanent': True}),
    url(ur'^kalhovd/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://kalhovd.turistforeningen.no/', 'permanent': True}),
    url(ur'^keipen/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://keipen.turistforeningen.no/', 'permanent': True}),
    url(ur'^kobberhaughytta/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://kobberhaughytta.turistforeningen.no/', 'permanent': True}),
    url(ur'^komdegut/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://komdegut.turistforeningen.no/', 'permanent': True}),
    url(ur'^kongsberg/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://kongsberg.turistforeningen.no/', 'permanent': True}),
    url(ur'^kraekkja/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://kraekkja.turistforeningen.no/', 'permanent': True}),
    url(ur'^krokan/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://krokan.turistforeningen.no/', 'permanent': True}),
    url(ur'^kvam/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://kvam.turistforeningen.no/', 'permanent': True}),
    url(ur'^kvinnherad/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://kvinnherad.turistforeningen.no/', 'permanent': True}),
    url(ur'^laerdal/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://laerdal.turistforeningen.no/', 'permanent': True}),
    url(ur'^larvik/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://larvik.turistforeningen.no/', 'permanent': True}),
    url(ur'^leikanger/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://leikanger.turistforeningen.no/', 'permanent': True}),
    url(ur'^lillehammer/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://lillehammer.turistforeningen.no/', 'permanent': True}),
    url(ur'^liomseter/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://liomseter.turistforeningen.no/', 'permanent': True}),
    url(ur'^litlos/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://litlos.turistforeningen.no/', 'permanent': True}),
    url(ur'^lofoten/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://lofoten.turistforeningen.no/', 'permanent': True}),
    url(ur'^luster/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://luster.turistforeningen.no/', 'permanent': True}),
    url(ur'^lysefjorden/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://lysefjorden.turistforeningen.no/', 'permanent': True}),
    url(ur'^midtrenordfjord/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://midtrenordfjord.turistforeningen.no/', 'permanent': True}),
    url(ur'^mogen/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://mogen.turistforeningen.no/', 'permanent': True}),
    url(ur'^narvik/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://narvik.turistforeningen.no/', 'permanent': True}),
    url(ur'^nedreglomma/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://nedreglomma.turistforeningen.no/', 'permanent': True}),
    url(ur'^nordhordland/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://nordhordland.turistforeningen.no/', 'permanent': True}),
    url(ur'^nordkapp/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://nordkapp.turistforeningen.no/', 'permanent': True}),
    url(ur'^nord-osterdal/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://nord-osterdal.turistforeningen.no/', 'permanent': True}),
    url(ur'^nord-salten/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://nord-salten.turistforeningen.no/', 'permanent': True}),
    url(ur'^nordstedalseter/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://nordstedalseter.turistforeningen.no/', 'permanent': True}),
    url(ur'^notodden/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://notodden.turistforeningen.no/', 'permanent': True}),
    url(ur'^ntt/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://ntt.turistforeningen.no/', 'permanent': True}),
    url(ur'^odal/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://odal.turistforeningen.no/', 'permanent': True}),
    url(ur'^odda-ullensvang/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://odda-ullensvang.turistforeningen.no/', 'permanent': True}),
    url(ur'^os/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://os.turistforeningen.no/', 'permanent': True}),
    url(ur'^preikestolen_basecamp/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://preikestolen_basecamp.turistforeningen.no/', 'permanent': True}),
    url(ur'^rana/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://rana.turistforeningen.no/', 'permanent': True}),
    url(ur'^rena/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://rena.turistforeningen.no/', 'permanent': True}),
    url(ur'^ringerike/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://ringerike.turistforeningen.no/', 'permanent': True}),
    url(ur'^rondanestien/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://rondanestien.turistforeningen.no/', 'permanent': True}),
    url(ur'^rondvassbu/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://rondvassbu.turistforeningen.no/', 'permanent': True}),
    url(ur'^sandefjord/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://sandefjord.turistforeningen.no/', 'permanent': True}),
    url(ur'^sandhaug/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://sandhaug.turistforeningen.no/', 'permanent': True}),
    url(ur'^sandnessjoen/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://sandnessjoen.turistforeningen.no/', 'permanent': True}),
    url(ur'^sauda/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://sauda.turistforeningen.no/', 'permanent': True}),
    url(ur'^senja/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://senja.turistforeningen.no/', 'permanent': True}),
    url(ur'^seterengard/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://seterengard.turistforeningen.no/', 'permanent': True}),
    url(ur'^skogadalsboen/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://skogadalsboen.turistforeningen.no/', 'permanent': True}),
    url(ur'^snøheim/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://snøheim.turistforeningen.no/', 'permanent': True}),
    url(ur'^sogndal/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://sogndal.turistforeningen.no/', 'permanent': True}),
    url(ur'^sognogfjordane/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://sognogfjordane.turistforeningen.no/', 'permanent': True}),
    url(ur'^solor/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://solor.turistforeningen.no/', 'permanent': True}),
    url(ur'^solund/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://solund.turistforeningen.no/', 'permanent': True}),
    url(ur'^sorvaranger/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://sorvaranger.turistforeningen.no/', 'permanent': True}),
    url(ur'^sotaseter/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://sotaseter.turistforeningen.no/', 'permanent': True}),
    url(ur'^stord-fitjar/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://stord-fitjar.turistforeningen.no/', 'permanent': True}),
    url(ur'^stranddalshytta/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://stranddalshytta.turistforeningen.no/', 'permanent': True}),
    url(ur'^sulitjelma/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://sulitjelma.turistforeningen.no/', 'permanent': True}),
    url(ur'^svukuriset/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://svukuriset.turistforeningen.no/', 'permanent': True}),
    url(ur'^telemark/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://telemark.turistforeningen.no/', 'permanent': True}),
    url(ur'^troms/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://troms.turistforeningen.no/', 'permanent': True}),
    url(ur'^tvedestrand_og_vegarshei/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://tvedestrand_og_vegarshei.turistforeningen.no/', 'permanent': True}),
    url(ur'^valdres/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://valdres.turistforeningen.no/', 'permanent': True}),
    url(ur'^vansjo/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://vansjo.turistforeningen.no/', 'permanent': True}),
    url(ur'^varangerhalvoya/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://varangerhalvoya.turistforeningen.no/', 'permanent': True}),
    url(ur'^vesteralen/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://vesteralen.turistforeningen.no/', 'permanent': True}),
    url(ur'^vik/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://vik.turistforeningen.no/', 'permanent': True}),
    url(ur'^voss/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://voss.turistforeningen.no/', 'permanent': True}),
    url(ur'^ynt/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://ynt.turistforeningen.no/', 'permanent': True}),
    url(ur'^ytresogn/(?P<slug>.*)', 'page.views.redirect', kwargs={'url': 'http://ytresogn.turistforeningen.no/', 'permanent': True}),
)
